// This file is generated by Slice Machine. Update with care!

import BlogContent from './BlogContent';
import Head from './Head';
import Quote from './Quote';

export {
	BlogContent,
	Head,
	Quote,
};

export const components = {
	blog_content: BlogContent,
	head: Head,
	quote: Quote,
};
